DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS drawings CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
);

CREATE TABLE drawings (
  users_id INTEGER REFRENCES users(id) ON DELETE CASCADE,
  drawing_name VARCHAR(255) NOT NULL,
  drawing_points JSON NOT NULL,
  is_showcase BOOLEAN NOT NULL DEFAULT FALSE 
);